[package]
name = "lzbt-systemd"
version.workspace = true
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.80"
base32ct = { version = "0.2.0", features = ["alloc"] }
stderrlog = "0.6.0"
log = { version = "0.4.20", features = ["std"] }
clap = { version = "4.5.1", features = ["derive"] }
lanzaboote_tool = { path = "../shared" }
indoc = "2.0.4"
serde_json = "1.0.114"
sha2 = "0.10.8"
tempfile = "3.10.1"
nix = { version = "0.28.0", default-features = false, features = [ "fs" ] }

[dev-dependencies]
assert_cmd = "2.0.14"
expect-test = "1.4.1"
filetime = "0.2.23"
rand = "0.8.5"
goblin = "0.7.1"
walkdir = "2.4.0"
